version: "3"
services:
  api:
    image: youtube:test9
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - data_1:/app/data/data_1
      - data_2:/app/data/data_2
      - data_3:/app/data/data_3
      - data_4:/app/data/data_4
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    image: postgres:15
    networks:
      - postgres
    ports:
      - "5000:5432"
    volumes:
      - PG:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: postgres
 
  pgadmin:
    image: dpage/pgadmin4:snapshot
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - PgAdmin4:/root/.pgadmin
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: nurik1kun@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "123123123"
 

volumes:
  PG:
    external: true
  PgAdmin4:
    external: true
  pgadmin:
    external: true
  data_1:
  data_2:
  data_3:
  data_4:
 
networks:
  postgres:
    driver: bridge